# Generated by Django 5.2.1 on 2026-01-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_menu_order_orderitem_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
