# Generated by Django 5.2.1 on 2026-01-30 05:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
